#!/bin/sh

# Fill the information below to your enviroment
username=
password=
baseurl=https://URL
site=default

[ -f ./unifi_sh_env ] && . ./unifi_sh_env

cookie=/tmp/unifi_cookie.$USER

curl_cmd="curl --tlsv1 --silent --cookie ${cookie} --cookie-jar ${cookie} --insecure "

named_args_to_payload() {
    payload=""
    for a in "$@" ; do
        if [ "${a##*=*}" = "" ] ; then
            k=`echo $a | cut -d = -f 1`
            v=`echo $a | cut -d = -f 2`
            payload="${payload}, '$k':'$v'"
        fi
    done
    echo ${payload}
}

unifi_requires() {
    if [ -z "$username" -o -z "$password" -o -z "$baseurl" -o -z "$site" ] ; then
        echo "Error! please define required env vars before including unifi_sh. E.g. "
        echo ""
        echo "export username=ubnt"
        echo "export password=ubnt"
        echo "export baseurl=https://localhost:8443"
        echo "export site=default"
        echo ""
        return
    fi
}

unifi_login() {
    # authenticate against unifi controller
    ${curl_cmd} --data "{'username':'$username', 'password':'$password'}" $baseurl/api/login > /dev/null
}

unifi_logout() {
    # logout
    ${curl_cmd} $baseurl/logout
}

unifi_api() {
    if [ $# -lt 1 ] ; then
        echo "Usage: $0 <uri> [json]"
        echo "    uri example /stat/sta "
        return
    fi
    uri=$1
    shift
    [ "${uri:0:1}" != "/" ] && uri="/$uri"
    json="$@"
    [ "$json" = "" ] && json="{}"
    ${curl_cmd} --data "$json" $baseurl/api/s/$site$uri
}

# cmd/stamgr
# authorize-guest(mac, minutes, [up=kbps, down=kbps, bytes=MB])
unifi_authorize_guest() {
    if [ $# -lt 2 ] ; then
        echo "Usage: $0 <mac> <minutes> [up=kbps] [down=kbps] [bytes=MB] [ap_mac=mac]"
        return
    fi

    mac=$1
    minutes=$2
    other_payload=`named_args_to_payload "$@"`

    ${curl_cmd} --data "json={'cmd':'authorize-guest', 'mac':'${mac}', 'minutes':${minutes}${other_payload}}" $baseurl/api/s/$site/cmd/stamgr
}

# cmd/stamgr
# unauthorize-guest(mac)
unifi_unauthorize_guest() {
    if [ $# -lt 1 ] ; then
        echo "Usage: $0 <mac>"
        return
    fi

    mac=$1

    ${curl_cmd} --data "json={'cmd':'unauthorize-guest', 'mac':'${mac}'}" $baseurl/api/s/$site/cmd/stamgr
}

# cmd/stamgr
# kick-sta(mac)
unifi_reconnect_sta() {
    if [ $# -lt 1 ] ; then
        echo "Usage: $0 <mac>"
        return
    fi

    mac=$1

    ${curl_cmd} --data "json={'cmd':'kick-sta', 'mac':'${mac}'}" $baseurl/api/s/$site/cmd/stamgr
}

# cmd/stamgr
# block-sta(mac)
unifi_block_sta() {
    if [ $# -lt 1 ] ; then
        echo "Usage: $0 <mac>"
        return
    fi

    mac=$1

    ${curl_cmd} --data "json={'cmd':'block-sta', 'mac':'${mac}'}" $baseurl/api/s/$site/cmd/stamgr
}

unifi_backup() {
    if [ "$1" = "" ]; then
        output=unifi-backup.unf # or `date +%Y%m%d`.unf
    else
        output=$1
    fi

    # ask controller to do a backup, response contains the path to the backup file
    path=`$curl_cmd --data "json={'cmd':'backup', 'days': '7'}" $baseurl/api/s/$site/cmd/system | sed -n 's/.*\(\/dl.*unf\).*/\1/p'`

    echo "Download path: $baseurl$path"
    # download the backup to the destinated output file
    $curl_cmd $baseurl$path -o $output
}

# cmd/hotspot
# create-voucher(expires, n, [note=notes, up=kbps, down=kbps, bytes=MB])
# @returns create_time
unifi_create_voucher() {
    if [ $# -lt 2 ] ; then
        echo "Usage: $0 <minutes> <n> [note=notes] [up=kbps] [down=kbps] [bytes=MB]"
        return
    fi
    minutes=$1
    n=$2
    other_payload=`named_args_to_payload "$@"`
    token=`${curl_cmd} --data "json={'cmd':'create-voucher','expire':${minutes},'n':$n ${other_payload}}" $baseurl/api/s/$site/cmd/hotspot \
        | sed -e 's/.*"create_time"\s*:\s*\([0-9]\+\).*/\1/'`
    echo "token=$token"
    if [ "$token" != "" ] ; then
        ${curl_cmd} --data "json={'create_time':${token}}" $baseurl/api/s/$site/stat/voucher
    fi
}

# stat/voucher
# query(create_time)
unifi_get_vouchers() {
    set -x
    if [ $# -lt 0 ] ; then
        echo "Usage: $0 [token]"
        return
    fi
    token=$1
    [ "$token" != "" ] && other_payload="'create_time':${token}"
    ${curl_cmd} --data "json={${other_payload}}" $baseurl/api/s/$site/stat/voucher
    echo ${curl_cmd} --data "json={${other_payload}}" $baseurl/api/s/$site/stat/voucher
}

# delete-voucher(id)
unifi_delete_voucher() {
    if [ $# -lt 1 ] ; then
        echo "Usage: $0 <id>"
        return
    fi
    id=$1
    ${curl_cmd} --data "json={'cmd':'delete-voucher','_id':'${id}'}" $baseurl/api/s/$site/cmd/hotspot
}

# stat/sta
unifi_list_sta() {
    ${curl_cmd} --data "json={}" $baseurl/api/s/$site/stat/sta
}

unifi_list_device() {
    if [ $# -lt 1 ] ; then
        echo "Usage: $0 <site> [<field name>]"
        return
    fi

    field=$2
    if [ -z "$field" ] ; then
      field=mac
    fi

    pycmd="import json, sys; obj=json.load(sys.stdin);\nfor x in obj['data']: print x['$field']"
    ${curl_cmd} --data "json={}" $baseurl/api/s/$1/stat/device | python -c "exec(\"$pycmd\")"
#    ${curl_cmd} $baseurl/api/s/$1/stat/device
}


unifi_list_device_state() {
    if [ $# -lt 1 ] ; then
        echo "Usage: $0 <site> "
        return
    fi
    #${curl_cmd} --data "json={}" $baseurl/api/s/$1/stat/device | python -m json.tool
    pycmd="import json, sys; obj=json.load(sys.stdin);\nfor x in obj['data']:\n    print '%s: %s' % (x['name'],(x['state'] if 'state' in x else '0'));"
    ${curl_cmd} $baseurl/api/s/$1/stat/device \
        | python -c "exec(\"$pycmd\")"
}

unifi_list_sites() {
    field=$1
    if [ -z "$field" ] ; then
      field=name
    fi
    pycmd="import json, sys; obj=json.load(sys.stdin);\nfor x in obj['data']:\n    print x['$field'].encode('iso-8859-1') if '$field' in x else ''"
#    pycmd="import json, sys; obj=json.load(sys.stdin);\nfor x in obj['data']:\n    print x['$field'] if '$field' in x else ''"
#    ${curl_cmd} --data "json={'cmd':'get-sites'}" $baseurl/api/cmd/sitemgr | python -c "exec(\"$pycmd\")"
    ${curl_cmd} $baseurl/api/self/sites | python -c "exec(\"$pycmd\")"
}

unifi_restart_device() {
    if [ $# -lt 2 ] ; then
        echo "Usage: $0 <site> <mac>"
        return
    fi
    ${curl_cmd} --data "json={'mac':'$2','cmd':'restart'}" $baseurl/api/s/$1/cmd/devmgr
}


unifi_requires

